import type { CatalogQuestion } from "@/lib/questionCatalog/types";

export const COIN_RARE_BONUS = 100;

export const RARE_QUESTIONS: CatalogQuestion[] = [
  {
    id: "rare-food-king",
    question: "THE FOOD KING DEMANDS: Is cereal soup?",
    category: "food",
    rarity: "rare",
    weight: 1,
    emoji: "🍕",
    optionA: "YES",
    optionB: "NO",
    votes: { percentA: 31, percentB: 69, total: 9_200_000, winner: "B" },
    special: true,
  },
  {
    id: "rare-chaos-queen",
    question: "CHAOS QUEEN ASKS: Does pineapple belong on pizza?",
    category: "chaos",
    rarity: "rare",
    weight: 1,
    emoji: "👑",
    optionA: "YES",
    optionB: "NO",
    votes: { percentA: 36, percentB: 64, total: 11_100_000, winner: "B" },
    special: true,
  },
  {
    id: "rare-algorithm",
    question: "THE ALGORITHM WANTS: Tabs or spaces?",
    category: "tech",
    rarity: "rare",
    weight: 1,
    emoji: "🤖",
    optionA: "TABS",
    optionB: "SPACES",
    votes: { percentA: 22, percentB: 78, total: 8_400_000, winner: "B" },
    special: true,
  },
  {
    id: "rare-timeline",
    question: "TIMELINE BREAKER: Is water wet?",
    category: "chaos",
    rarity: "rare",
    weight: 1,
    emoji: "⭐",
    optionA: "YES",
    optionB: "NO",
    votes: { percentA: 64, percentB: 36, total: 14_200_000, winner: "A" },
    special: true,
  },
  {
    id: "rare-viral",
    question: "GOING VIRAL: Is a hot dog a sandwich?",
    category: "internet",
    rarity: "rare",
    weight: 1,
    emoji: "📱",
    optionA: "YES",
    optionB: "NO",
    votes: { percentA: 57, percentB: 43, total: 18_900_000, winner: "A" },
    special: true,
  },
];
